# Generated by Django 2.0.7 on 2018-07-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneUploadAnonymous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('scene_img', models.FileField(upload_to='scene/anonymous')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
