# Generated by Django 2.0.7 on 2018-07-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.FileField(upload_to='scene')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
