# Generated by Django 2.0.7 on 2018-07-28 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SceneUploadAnonymous',
        ),
        migrations.AlterField(
            model_name='sceneupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
